dist:
	rm -f euhwc-recent-posts-widget.zip
	zip -r euhwc-recent-posts-widget.zip . -x euhwc-recent-posts-widget.zip Makefile .gitignore

clean:
	rm -rf euhwc-recent-posts-widget.zip

.PHONY: dist clean
